export const products = {
    'Laptops': {
        'Acer': {
            'Aspire 7': {
                'image': 'https://i.ibb.co/DWxjXr4/acer-aspire-7.jpg',
                'details': {
                    'brand name': 'Acer',
                    'series': 'Acer Aspire',
                    'item model number': 'A715-72G-71CT',
                    'display': '15. 6" Full HD (1920 x 1080) widescreen LED-backlit IPS',
                    'color': 'GTX 1050Ti graphics',
                    'processor': 'Intel Core i7-9800U 2 40 GHz',
                    'memory': '16GB DDR4 2400MHz',
                    'ssd': '512GB PCIe NVMe',
                    'operating system': 'Windows 10',
                    'wireless type': '802.11ac',
                    'product dimensions': '10.35 x 15.02 x 0.94 inches',
                    'graphics coprocessor': 'NVIDIA GeForce GTX 1050 Ti',
                    'chipset brand': 'NVIDIA',
                    'number of USB 2.0 ports': '2',
                    'number of USB 3.0 ports': '3',
                    'batteries': '1 Lithium ion batteries required. (included)',
                    'battery life': 'Up to 7 hours',
                    'item weight': '5.18 pounds',
                },
                'price': 929.65,
                'quantity': 0,
            },
        },

        'HP': {
            'Pavilion': {
                'image': 'https://i.ibb.co/tBj7yDb/hp-pavilion.jpg',
                'details': {
                    'brand name': 'HP',
                    'series': 'HP Pavilion',
                    'item model number': '14M-DH1003DX',
                    'display': '13.3-inch diagonal FHD IPS BrightView',
                    'processor': 'Intel Core i5-9600K 2 40 GHz',
                    'memory': '8 GB DDR4-2400 SDRAM',
                    'ssd': '256 GB PCIe(R) NVMe(TM) M.2 Solid State Drive',
                    'os': 'Windows 10 Home',
                    'graphics coprocessor': 'NVIDIA GeForce GTX 1050 3GB',
                    'chipset brand': 'NVIDIA',
                    'number of USB 2.0 ports': '2',
                    'number of USB 3.0 ports': '4',
                    'item dimensions': '12.80 x 8.80 x 0.80 inches',
                    'item weight': '7.41 ounces',
                    'batteries': '1 Lithium ion batteries required. (included)',
                    'battery life': 'Up to 11 hours',
                },
                'price': 684.25,
                'quantity': 0,
            },
        },

        'Dell': {
            'Latitude': {
                'image': 'https://i.ibb.co/Zc05K3P/dell-latitude.jpg',
                'details': {
                    'brand name': 'Dell',
                    'series': 'Dell Latitude',
                    'display': '14-inch (1366x768) widescreen IPS',
                    'processor': 'Intel Core i5-6300U 2 40 GHz',
                    'memory': '8 GB DDR4 2133 MHz',
                    'ssd': '256 GB PCIe(R)',
                    'graphics coprocessor': 'NVIDIA GeForce GTX 1050 8GB',
                    'chipset brand': 'NVIDIA',
                    'number of USB 2.0 ports': '2',
                    'number of USB 3.0 ports': '4',
                    'item dimensions': '8.80 x 13.50 x 0.80 inches',
                    'item weight': '7.41 ounces',
                    'batteries': '1 Lithium ion batteries required. (included)',
                    'battery life': 'Up to 5 hours',
                    'os': 'Windows 10 Professional 64-bit',
                },
                'price': 399.50,
                'quantity': 0,
            },
        },
    },

    'Phones': {
        'IPhone': {
            'IPhone3': {
                'image': 'https://i.ibb.co/0ncTfqq/iphone3.jpg',
                'details': {
                    'display': 'TFT capacitive touchscreen, 16M colors',
                    'network': 'GSM / HSPA',
                    'processor': '600 MHz Cortex-A8',
                    'hard drive': '8GB',
                    'card slot': 'No',
                    'memory': '256 RAM',
                    'os': 'iOS 3, upgradable to iOS 6.1.6',
                    'main camera': '3.15 MP, f/2.8, AF',
                    'selfie camera': 'No',
                    'sound': 'Loudspeaker, 3.5mm jack',
                    'sensors': 'Accelerometer, proximity, compass',
                    'dimensions': '115.5 x 62.1 x 12.3 mm (4.55 x 2.44 x 0.48 in)',
                    'weight': '135 g (4.76 oz)',
                    'battery': 'Non-removable Li-Ion battery',
                    'USB': '2.0',
                },
                'price': 110,
                'quantity': 0,
            },

            'IPhone4': {
                'image': 'https://i.ibb.co/cJZbdcX/iphone4.jpg',
                'details': {
                    'display': 'IPS LCD capacitive touchscreen, 16M colors',
                    'network': 'GSM / CDMA / HSPA / EVDO',
                    'processor': 'Dual-core 1.0 GHz Cortex-A9',
                    'hard drive': '16GB',
                    'memory': '512MB RAM',
                    'card slot': 'No',
                    'os': 'iOS 5, upgradable to iOS 9.3.5',
                    'main camera': '8 MP, f/2.4, 35mm (standard), 1/3.2", 1.4µm, AF',
                    'selfie camera': 'VGA, videocalling over Wi-Fi and 3G',
                    'sound': 'Loudspeaker, 3.5mm jack',
                    'sensors': 'Accelerometer, gyro, proximity, compass',
                    'dimensions': '115.2 x 58.6 x 9.3 mm (4.54 x 2.31 x 0.37 in)',
                    'weight': '140 g (4.94 oz)',
                    'battery': 'Non-removable Li-Po 1432 mAh battery (5.3 Wh)',
                    'USB': '2.0',
                },
                'price': 190,
                'quantity': 0,
            },
        },

        'CAT': {
            'S41': {
                'image': 'https://i.ibb.co/0s7kMkq/cat-s41.jpg',
                'details': {
                    'display': 'IPS LCD capacitive touchscreen, 16M colors',
                    'network': 'GSM / HSPA / LTE',
                    'processor': 'Quad-core 1.8 GHz Cortex-A53',
                    'hard drive': '32GB',
                    'card slot': 'microSDXC (dedicated slot)',
                    'memory': '3GB RAM',
                    'os': 'Android 10, planned upgrade to Android 11.0',
                    'main camera': '13 MP, PDAF',
                    'selfie camera': '8 MP',
                    'sound': 'Loudspeaker, 3.5mm jack',
                    'sensors': 'Accelerometer, proximity, compass',
                    'dimensions': '152 x 75 x 12.9 mm (5.98 x 2.95 x 0.51 in)',
                    'weight': '218 g (7.69 oz)',
                    'battery': 'Non-removable Li-Po 4200 mAh battery',
                    'USB': 'microUSB 2.0, USB On-The-Go',
                },
                'price': 450,
                'quantity': 0,
            },

            'S61': {
                'image': 'https://i.ibb.co/h9J88mL/cat-s61.jpg',
                'details': {
                    'display': 'IPS LCD capacitive touchscreen, 16M colors',
                    'network': 'GSM / CDMA / HSPA / LTE / 5G',
                    'processor': 'Octa-core (8x2.6 GHz Cortex-A76)',
                    'hard drive': '128GB',
                    'memory': '8GB RAM',
                    'os': 'Android 10, MIUI 11',
                    'main camera': '16 MP, PDAF, FLIR thermal camera (Lepton module)',
                    'selfie camera': '8 MP',
                    'sound': 'Loudspeaker, 3.5mm jack',
                    'sensors': 'Accelerometer, gyro, proximity, compass, barometer, indoor air quality sensor',
                    'dimensions': '163 x 78 x 13 mm (6.42 x 3.07 x 0.51 in)',
                    'weight': '250 g (8.82 oz)',
                    'battery': 'Non-removable Li-Ion 4500 mAh battery',
                    'USB': '2.0, Type-C 1.0 reversible connector, USB On-The-Go',
                },
                'price': 900,
                'quantity': 0,
            },
        },

        'Xiaomi': {
            'Redmi 10x': {
                'image': 'https://i.ibb.co/vYC8dkV/xiaomi-redmi-10x.jpg',
                'details': {
                    'display': 'AMOLED capacitive touchscreen, 16M colors',
                    'network': 'GSM / HSPA / LTE',
                    'processor': 'Quad-core 1.8 GHz Cortex-A53',
                    'hard drive': '32GB',
                    'memory': '3GB RAM',
                    'os': 'Android 10, planned upgrade to Android 11.0',
                    'main camera': '48 MP, f/1.8, 26mm (wide), 1/2.0", 0.8µm, PDAF',
                    'selfie camera': '20 MP, 26mm (wide)',
                    'sound': 'Loudspeaker, 3.5mm jack, 24-bit/192kHz audio',
                    'sensors': 'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass\n',
                    'dimensions': '164.2 x 75.8 x 9 mm (6.46 x 2.98 x 0.35 in)\n',
                    'weight': '208 g (7.34 oz)',
                    'battery': 'Non-removable Li-Po 4200 mAh battery',
                    'USB': '2.0, Type-C 1.0 reversible connector, USB On-The-Go',
                    'price': 300,
                },
                'price': 900,
                'quantity': 0,
            },
        },
    },
};